### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by samoht** [cryptosense/multipart-form-data#10]
Would be great to cut a first release on opam, so that https://github.com/ocaml/opam-repository/pull/7981 could be merged :-)

Thanks!

**Comment by emillon** [comment]
Sure! I thought that it would be simpler to integrate into `cohttp` but in the meantime I'll cut a release this week.

**Comment by emillon** [comment]
[Pull-requested](https://github.com/ocaml/opam-repository/pull/8003) ! I'll need to clean up the API a bit, so expected a new version some day (hopefully soon) but in the meantime you can use this version without pinning.

Thanks!

**Comment by samoht** [comment]
Thanks!
