### ISSUE TITLE
How to tell the size of the file?

### ISSUE THREAD

**Issue by sgrove** [cryptosense/multipart-form-data#15]
Right now we can get the name of a File via `Multipart.file_name`, and the body via `Multipart.file_stream file` - how can I get the number of bytes in the file?

**Comment by emillon** [comment]
Hi,

Generally speaking, that information is not available at that level. You can have an approximation using the whole request's Content-Length (if present), but for example if there are several files in the request you can't know without consuming the whole file.

Hope that helps!
